[package]
name = "acpd"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1"
async-trait = "0.1.89"
axum = "0.8"
nix = { version = "0.29", features = ["signal", "fs", "user"] }
sd-notify = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["full"] }
toml = "0.8"
tracing = "0.1"
tracing-journald = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
